POST http://localhost:9000/auth/signup
content-type: application/json

{
    "firstname": "Chabin",
    "lastname": "kukiel",
    "username": "Chabina",
    "email": "kabin3@gmail.com",
    "password": "hello"
}

###
POST http://localhost:9000/auth/login
content-type: application/json

{
    "email": "chabin3@gmail.com",
    "password": "hello"
}